### PR TITLE
feat: add initial spaces with schema definition

### LINKED ISSUE #5: Add schema checker as CI job

### PR DESCRIPTION
**Pull request by mariusheine**
Addressing #1 with some initial coworking spaces in schleswig-holstein, germany

closes #5

### CODE REVIEW

**Comment by ellenheine** [comment]
@anbraten @lukashass I added 4 spaces for testing if we want to connect it to bookyp. Maybe someone wants to review it.

**Comment by anbraten** [comment]
@ellenheine @mariusheine Looks nice. Now as I am seeing the file, I would still consider using yml instead of json to use features like multi line strings. What do you think?

```yml
spaces:
  - name: cobaas - Coworking Space Preetz
    id: de-preetz-cobaas
    address: |
      Baasberg 1
      24211 Preetz
    location:
      lat: 54.2279307
      lon: 10.2808406
    email: info@cobaas.de
    phone: +491754177872
    description: |
      Mal raus und den Kopf frei bekommen, nicht jeden Tag pendeln müssen und in einer kreativen Umgebung arbeiten - das ist unser Angebot.
      Mobiles, temporäres Arbeiten in der Holsteinischen Schweiz in unmittelbarer Nähe zum Kirchsee und der Schwentine.
    links:
      - name: website
        url: https://www.cobaas.de/
      - name: instagram
        url: https://www.instagram.com/cobaas_preetz/
      - name: facebook
        url: https://www.facebook.com/people/Cobaas-Coworking-Space-Preetz/100066414680880/
      - name: linkedin
        url: https://www.linkedin.com/company/cobaas-coworking-space-preetz/
    logo: https://image.jimcdn.com/app/cms/image/transf/dimension=1040x10000:format=png/path/sedcf87c7f3e9fb47/image/ib0d0d7919f26ae32/version/1668766083/image.png
    images:
      - url: https://image.jimcdn.com/app/cms/image/transf/dimension=2048x2048:format=jpg/path/sedcf87c7f3e9fb47/image/i782d80b67a506847/version/1620979184/image.jpg
        alt: Pavillions des cobaas Coworking Space Preetz

```

**Comment by ellenheine** [comment]
@anbraten ok, you are right that looks nicer. I just saw an example yml and that looked weird. So let's take yours. Do you change it or should we?

**Comment by anbraten** [comment]
@ellenheine I can change it.

**Review by anbraten — APPROVED** [review]

**Comment by mariusheine** [comment]
@anbraten Awesome also with the schema checker

**Pull request merged**
